version: "3"

services:
  redis:
    image: redis:6.2-alpine
    restart: always
    command: redis-server --save 20 1 --loglevel warning --requirepass 25801ec1eacbb3ee69c16761d573e0e6ae03bf3eb15682cee541b4b599de8977
    volumes:
      - redis:/data

  mongodb:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongo:/data/db

  api:
    build: .
    container_name: api-server
    image: api/image
    command: yarn start:prod
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - mongodb
      - redis

volumes:
  mongo:
  redis:
    driver: local
