version: "3"

services:
  redis:
    image: redis:6.2-alpine
    restart: always
    command:
      - /bin/sh
      - -c
      - redis-server --save 20 1 --loglevel debug --requirepass "$${REDIS_PASSWORD:?REDIS_PASSWORD variable is not set}"
    env_file:
      - .env
    volumes:
      - redis:/data

  mongodb:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    env_file:
      - .env
    volumes:
      - mongo:/data/db

  api:
    build: .
    container_name: api-server
    image: api/image
    command: yarn start:prod
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - mongodb
      - redis

volumes:
  mongo:
  redis:
    driver: local
